FROM node:20.19-trixie-slim

WORKDIR /app

ARG DEBIAN_FRONTEND=noninteractive
ENV NG_CLI_ANALYTICS=ci

# Make sure wget and curl are installed
RUN apt-get update
RUN apt-get install wget curl gnupg -y

# Download and setup google chrome repository
RUN curl -s https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list

# Perform package management for image usage to build/test angular apps
RUN apt update
RUN apt install -y google-chrome-stable
RUN apt upgrade -y

# Make sure we run the latest npm version and install the latest angular/cli version
RUN npm -g install npm@10.8.2
RUN npm install -g @angular/cli

# No entry point, run it your build/tests via a script, cmd example:
# docker run -it -v $(pwd):/app --entrypoint ./<your_node_npm_script>.sh <container_name>
